### ISSUE TITLE
Update privacy practice information in chrome extension store

### ISSUE THREAD

**Issue by wdhongtw** [wdhongtw/markdown-link#2]
As JayBeeDe states in #1 , it will be much better if we provide the reason for each permission we request from user.

**Comment by JayBeeDe** [comment]
In [Developer Dashboard](https://chrome.google.com/webstore/developer/dashboard), in the extension Privacy page, I suggest to write the following content:

# Field Single purpose

When clicking the extension icon or using a keyboard shortcut, this extension is reading the URL of the current web page , eventually applying a regex filter on it (depending on the user settings), and copying a markdown link to the clipboard.

# Fields Permissions justifications

## activeTab justification

When clicking the extension icon or using a keyboard shortcut, the extension needs to know the current URL in order to generate the markdown link. 

## clipboardWrite justification

When clicking the extension icon or using a keyboard shortcut, markdown link will be generated and copied to your clipboard. Note that this extension doesn't not read data from your clipboard.

## downloads justification

When exporting the extension settings, download permission is used.

## scripting justification

When clicking the extension icon or using a keyboard shortcut, markdown link will be generated and copied to your clipboard. To do so, extension needs to add temporary a hidden HTML `textarea` field in the document tree to copy it to the clipboard afterward. 

## storage justification

As soon as custom extension settings are set, storage will be used. If Google synchronization service is enabled in your web browser, it will be used to keep settings synchronized.

## remote code

Are you using remote code? -> No

# Data usage

## What user data do you plan to collect from users now or in the future?

uncheck all

## I certify that the following disclosures are true:

check all

**Comment by wdhongtw** [comment]
Submitted for publishment.
